{% set name = "capstone" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aquynh/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 7c81d798022f81e7507f1a60d6817f63aa76e489aa4e7055255f21a22f5e526a
  patches:  # [osx]
    - osx.patch  # [osx]

build:
  number: 3
  skip: true  # [py < 30]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - make
    - cmake  # [win]
  host:
    - python
    - pip
    - cython
    - pthread-stubs
  run:
    - python
    - setuptools

test:
  imports:
    - capstone

about:
  home: http://www.capstone-engine.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: The Ultimate Disassembler
  description: |
    Capstone is a lightweight multi-platform, multi-architecture disassembly framework
  doc_url: http://www.capstone-engine.org/documentation.html
  dev_url: https://github.com/aquynh/capstone

extra:
  recipe-maintainers:
    - scopatz
    - CJ-Wright
    - thewchan
