{% set name = "capstone" %}
{% set version_archive = "6.0.0-Alpha4" %}
{% set version = "6.0.0a4" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/aquynh/{{ name }}/archive/{{ version_archive }}.tar.gz
  sha256: af30a34af415123197b28072afaa9e0fd2c4c90daf70528cbcd13d5577e7a28c
  patches:
    - 0001-Thin-build-on-osx-64.patch

build:
  number: 0

outputs:
  - name: libcapstone
    script: install-lib.sh
    build:
      skip: true  # [win]
      run_exports:
        - {{ pin_subpackage("libcapstone", max_pin="x.x.x") }}
    requirements:
      build:
        - cmake
        - make
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
    test:
      commands:
        - test -f $PREFIX/lib/libcapstone${SHLIB_EXT}
  - name: cstool
    script: install-lib.sh
    build:
      skip: true  # [win]
      run_exports:
        - {{ pin_subpackage("libcapstone", max_pin="x.x.x") }}
    requirements:
      build:
        - cmake
        - make
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
      host:
        - {{ pin_subpackage('libcapstone', exact=True) }}
      run:
        - {{ pin_subpackage('libcapstone', exact=True) }}
    test:
      commands:
        - cstool -v
  - name: capstone
    script: install-py.sh  # [unix]
    script: install-py.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make
        - cmake
      host:
        - python
        - pip
        - cython
        - pthread-stubs
        - {{ pin_subpackage('libcapstone', exact=True) }}  # [not win]
        - setuptools
      run:
        - python
        - setuptools
        - importlib_resources
        - {{ pin_subpackage('libcapstone', exact=True) }}  # [not win]
    test:
      imports:
        - capstone
      requires:
        - pip
      commands:
        - pip check

about:
  home: http://www.capstone-engine.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSES/LICENSE.TXT
  summary: The Ultimate Disassembler
  description: |
    Capstone is a lightweight multi-platform, multi-architecture disassembly framework
  doc_url: http://www.capstone-engine.org/documentation.html
  dev_url: https://github.com/aquynh/capstone

extra:
  feedstock-name: capstone
  recipe-maintainers:
    - scopatz
    - CJ-Wright
    - thewchan
    - xhochy
