{% set name = "capstone" %}
{% set version = "5.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aquynh/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 2b9c66915923fdc42e0e32e2a9d7d83d3534a45bb235e163a70047951890c01a
  patches:   # [osx]
    - osx.patch  # [osx]

build:
  number: 0
  skip: true  # [py < 30]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - make
    - cmake  # [win]
  host:
    - python
    - pip
    - cython
    - pthread-stubs
  run:
    - python
    - setuptools

test:
  imports:
    - capstone

about:
  home: http://www.capstone-engine.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: The Ultimate Disassembler
  description: |
    Capstone is a lightweight multi-platform, multi-architecture disassembly framework
  doc_url: http://www.capstone-engine.org/documentation.html
  dev_url: https://github.com/aquynh/capstone

extra:
  recipe-maintainers:
    - scopatz
    - CJ-Wright
    - thewchan
