{% set name = "capstone" %}
{% set version = "5.0.2" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/aquynh/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 9d0be727cc942075a1696f576b88918eb0daf9db7a02f563f0c4e51a439a611d
  patches:
    - osx.patch  # [osx]

build:
  number: 0

outputs:
  - name: libcapstone
    script: install-lib.sh
    build:
      skip: true  # [win]
      run_exports:
        - {{ pin_subpackage("libcapstone", max_pin="x.x.x") }}
    requirements:
      build:
        - cmake
        - make
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
    test:
      commands:
        - test -f $PREFIX/lib/libcapstone${SHLIB_EXT}
  - name: cstool
    script: install-lib.sh
    build:
      skip: true  # [win]
      run_exports:
        - {{ pin_subpackage("libcapstone", max_pin="x.x.x") }}
    requirements:
      build:
        - cmake
        - make
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
      host:
        - {{ pin_subpackage('libcapstone', exact=True) }}
      run:
        - {{ pin_subpackage('libcapstone', exact=True) }}
    test:
      commands:
        - cstool -v
  - name: capstone
    script: install-py.sh  # [unix]
    script: install-py.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make
        - cmake  # [win]
      host:
        - python
        - pip
        - cython
        - pthread-stubs
        - {{ pin_subpackage('libcapstone', exact=True) }}  # [not win]
      run:
        - python
        - setuptools
        - importlib_resources
        - {{ pin_subpackage('libcapstone', exact=True) }}  # [not win]
    test:
      imports:
        - capstone
      requires:
        - pip
      commands:
        - pip check

about:
  home: http://www.capstone-engine.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: The Ultimate Disassembler
  description: |
    Capstone is a lightweight multi-platform, multi-architecture disassembly framework
  doc_url: http://www.capstone-engine.org/documentation.html
  dev_url: https://github.com/aquynh/capstone

extra:
  feedstock-name: capstone
  recipe-maintainers:
    - scopatz
    - CJ-Wright
    - thewchan
    - xhochy
